server:
  port: 8022
debug: true
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/karbasha_rescue
    username: keycloak
    password: password
  jpa:
    database: POSTGRESQL
    showSql: true
    generateDdl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddlAuto: validate
        jdbc:
          lob:
            non_contextual_creation: true
keycloak:
  principal-attribute: preferred_username
  auth-server-url: http://localhost:8088/auth
  realm: Karbasha
  resource: karbasha-rescue
  public-client: true
flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  schemas: karbasha_rescue
#  security-constraints:
#    - authRoles:
#        - user
#      securityCollections:
#        - patterns:
#            - /customers/*